[build]

command = "npm run production"
publish = "build_production"

[template.environment]
  BASE_URL_STAGING = "url to your PRODUCTION environment"
  BASE_URL_PRODUCTION = "url to your PRODUCTION environment"
