[build]

command = "npm run prod"
publish = "build_production"
#environment = { PHP_VERSION = "8.0", NODE_VERSION = "14" }

[template.environment]
  BASE_URL_STAGING = "url to your PRODUCTION environment"
  BASE_URL_PRODUCTION = "url to your PRODUCTION environment"
